title: Erica Ardian # Persepolis
logo: "/images/persepolis logo.png?raw=true" # Persepolis
description: > # ArdianGITHubEx
  MIS480CapstoneEExamplesGIT 
  <br><br>
  Conversions/ SEO 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
